create extension if not exists pgcrypto;

create table if not exists public.facilities (
    id uuid primary key default gen_random_uuid(),
    code text not null unique,
    name text not null,
    testing_plan text not null default 'starter',
    created_at timestamptz not null default now()
);

create table if not exists public.staff_profiles (
    id uuid primary key references auth.users (id) on delete cascade,
    facility_id uuid not null references public.facilities (id) on delete cascade,
    role text not null,
    display_name text not null,
    subscription_tier text not null default 'starter',
    beta_track text not null default 'care',
    is_demo boolean not null default false,
    created_at timestamptz not null default now(),
    constraint staff_profiles_role_check check (role in ('creator', 'admin', 'administrator', 'tester', 'nurse', 'carer', 'caregiver')),
    constraint staff_profiles_subscription_check check (subscription_tier in ('starter', 'carePro', 'careTeam'))
);

create table if not exists public.residents (
    id uuid primary key default gen_random_uuid(),
    facility_id uuid not null references public.facilities (id) on delete cascade,
    name text not null,
    risk_level text,
    date_of_birth date,
    room_label text,
    created_at timestamptz not null default now(),
    constraint residents_risk_level_check check (risk_level is null or risk_level in ('low', 'medium', 'high'))
);

create table if not exists public.alerts (
    id bigint generated by default as identity primary key,
    facility_id uuid not null references public.facilities (id) on delete cascade,
    resident_id uuid not null references public.residents (id) on delete cascade,
    type text not null,
    status text not null default 'open',
    priority integer not null default 1,
    assigned_to uuid references public.staff_profiles (id) on delete set null,
    created_at timestamptz not null default now(),
    acknowledged_at timestamptz,
    closed_at timestamptz,
    close_notes text,
    constraint alerts_type_check check (type in ('fall', 'sos')),
    constraint alerts_status_check check (status in ('open', 'acknowledged', 'closed'))
);

create table if not exists public.vital_events (
    id bigint generated by default as identity primary key,
    facility_id uuid not null references public.facilities (id) on delete cascade,
    resident_id uuid not null references public.residents (id) on delete cascade,
    metric text not null,
    value double precision not null,
    observed_at timestamptz not null default now(),
    recorded_by uuid references public.staff_profiles (id) on delete set null
);

create table if not exists public.handoff_requests (
    id bigint generated by default as identity primary key,
    facility_id uuid not null references public.facilities (id) on delete cascade,
    resident_id uuid not null references public.residents (id) on delete cascade,
    notes text,
    request_token text not null default gen_random_uuid()::text unique,
    created_at timestamptz not null default now(),
    resolved_at timestamptz,
    resolved_by uuid references public.staff_profiles (id) on delete set null
);

create index if not exists idx_staff_profiles_facility_id on public.staff_profiles (facility_id);
create index if not exists idx_residents_facility_id on public.residents (facility_id);
create index if not exists idx_alerts_facility_status_created_at on public.alerts (facility_id, status, created_at desc);
create index if not exists idx_alerts_resident_type_created_at on public.alerts (resident_id, type, created_at desc);
create index if not exists idx_vital_events_resident_observed_at on public.vital_events (resident_id, observed_at desc);
create index if not exists idx_handoff_requests_facility_created_at on public.handoff_requests (facility_id, created_at desc)
    where resolved_at is null;

create or replace function public.current_staff_facility_id()
returns uuid
language sql
stable
as $$
    select facility_id
    from public.staff_profiles
    where id = auth.uid()
$$;

alter table public.staff_profiles enable row level security;
alter table public.residents enable row level security;
alter table public.alerts enable row level security;
alter table public.vital_events enable row level security;
alter table public.handoff_requests enable row level security;

drop policy if exists "staff profile self read" on public.staff_profiles;
create policy "staff profile self read"
on public.staff_profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "facility resident read" on public.residents;
create policy "facility resident read"
on public.residents
for select
to authenticated
using (facility_id = public.current_staff_facility_id());

drop policy if exists "facility alert read" on public.alerts;
create policy "facility alert read"
on public.alerts
for select
to authenticated
using (facility_id = public.current_staff_facility_id());

drop policy if exists "facility alert update" on public.alerts;
create policy "facility alert update"
on public.alerts
for update
to authenticated
using (facility_id = public.current_staff_facility_id())
with check (facility_id = public.current_staff_facility_id());

drop policy if exists "facility vital read" on public.vital_events;
create policy "facility vital read"
on public.vital_events
for select
to authenticated
using (facility_id = public.current_staff_facility_id());

drop policy if exists "facility handoff read" on public.handoff_requests;
create policy "facility handoff read"
on public.handoff_requests
for select
to authenticated
using (facility_id = public.current_staff_facility_id());

drop policy if exists "facility handoff update" on public.handoff_requests;
create policy "facility handoff update"
on public.handoff_requests
for update
to authenticated
using (facility_id = public.current_staff_facility_id())
with check (facility_id = public.current_staff_facility_id());

insert into public.facilities (id, code, name, testing_plan)
values
    ('99999999-1111-4111-8111-111111111111', 'creator-hq', 'Creator Validation Facility', 'careTeam'),
    ('99999999-2222-4222-8222-222222222222', 'admin-demo', 'Administrator Demo Facility', 'careTeam'),
    ('99999999-3333-4333-8333-333333333333', 'care-team-demo', 'Care Team Demo Facility', 'careTeam'),
    ('99999999-4444-4444-8444-444444444444', 'care-pro-demo', 'Care Pro Demo Facility', 'carePro'),
    ('99999999-5555-4555-8555-555555555555', 'starter-demo', 'Starter Tester Facility', 'starter')
on conflict (id) do update
set code = excluded.code,
    name = excluded.name,
    testing_plan = excluded.testing_plan;

insert into public.residents (id, facility_id, name, risk_level, date_of_birth, room_label)
values
    ('11111111-1111-4111-8111-111111111111', '99999999-2222-4222-8222-222222222222', 'Margaret Lewis', 'high', '1941-03-14', 'Room 12'),
    ('11111111-2222-4222-8222-222222222222', '99999999-2222-4222-8222-222222222222', 'David Wright', 'medium', '1938-09-22', 'Room 15'),
    ('11111111-3333-4333-8333-333333333333', '99999999-3333-4333-8333-333333333333', 'Lillian Fraser', 'high', '1936-05-05', 'Room 7'),
    ('11111111-4444-4444-8444-444444444444', '99999999-3333-4333-8333-333333333333', 'Peter Ofori', 'low', '1944-01-18', 'Room 9'),
    ('11111111-5555-4555-8555-555555555555', '99999999-4444-4444-8444-444444444444', 'Emma Davis Demo', 'medium', '1942-11-02', 'Room 4'),
    ('11111111-6666-4666-8666-666666666666', '99999999-5555-4555-8555-555555555555', 'Family Preview Resident', 'low', '1947-07-27', 'Room 2')
on conflict (id) do update
set facility_id = excluded.facility_id,
    name = excluded.name,
    risk_level = excluded.risk_level,
    date_of_birth = excluded.date_of_birth,
    room_label = excluded.room_label;

insert into public.vital_events (facility_id, resident_id, metric, value, observed_at)
select *
from (
    values
        ('99999999-2222-4222-8222-222222222222'::uuid, '11111111-1111-4111-8111-111111111111'::uuid, 'temperature', 36.8::double precision, now() - interval '2 hours'),
        ('99999999-2222-4222-8222-222222222222'::uuid, '11111111-2222-4222-8222-222222222222'::uuid, 'heart_rate', 74::double precision, now() - interval '50 minutes'),
        ('99999999-3333-4333-8333-333333333333'::uuid, '11111111-3333-4333-8333-333333333333'::uuid, 'oxygen', 97::double precision, now() - interval '35 minutes'),
        ('99999999-4444-4444-8444-444444444444'::uuid, '11111111-5555-4555-8555-555555555555'::uuid, 'blood_pressure_systolic', 122::double precision, now() - interval '25 minutes')
) as seed(facility_id, resident_id, metric, value, observed_at)
where not exists (
    select 1
    from public.vital_events existing
    where existing.resident_id = seed.resident_id
      and existing.metric = seed.metric
);

insert into public.alerts (facility_id, resident_id, type, status, priority, created_at)
select *
from (
    values
        ('99999999-2222-4222-8222-222222222222'::uuid, '11111111-1111-4111-8111-111111111111'::uuid, 'fall', 'open', 3, now() - interval '20 minutes'),
        ('99999999-3333-4333-8333-333333333333'::uuid, '11111111-3333-4333-8333-333333333333'::uuid, 'sos', 'acknowledged', 2, now() - interval '45 minutes'),
        ('99999999-4444-4444-8444-444444444444'::uuid, '11111111-5555-4555-8555-555555555555'::uuid, 'fall', 'closed', 1, now() - interval '1 day')
) as seed(facility_id, resident_id, type, status, priority, created_at)
where not exists (
    select 1
    from public.alerts existing
    where existing.resident_id = seed.resident_id
      and existing.type = seed.type
      and existing.status = seed.status
);

create or replace function public.get_staff_info(p_user_id uuid)
returns table (
    id text,
    facility_id text,
    role text,
    display_name text
)
language sql
security definer
set search_path = public
as $$
    select sp.id::text, sp.facility_id::text, sp.role, sp.display_name
    from public.staff_profiles sp
    where sp.id = p_user_id
$$;

create or replace function public.create_fall_alert(
    p_facility_id uuid,
    p_resident_id uuid,
    p_priority integer default 2
)
returns table (alert_id bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.alerts (facility_id, resident_id, type, status, priority)
    values (p_facility_id, p_resident_id, 'fall', 'open', greatest(coalesce(p_priority, 2), 1))
    returning id into alert_id;

    return next;
end;
$$;

create or replace function public.create_sos_alert(
    p_facility_id uuid,
    p_resident_id uuid
)
returns table (alert_id bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.alerts (facility_id, resident_id, type, status, priority)
    values (p_facility_id, p_resident_id, 'sos', 'open', 3)
    returning id into alert_id;

    return next;
end;
$$;

create or replace function public.get_open_alerts_for_facility(p_facility_id uuid)
returns table (
    id bigint,
    resident_id uuid,
    type text,
    status text,
    priority integer,
    created_at timestamptz,
    assigned_to uuid
)
language sql
security definer
set search_path = public
as $$
    select a.id, a.resident_id, a.type, a.status, a.priority, a.created_at, a.assigned_to
    from public.alerts a
    where a.facility_id = p_facility_id
      and a.status <> 'closed'
    order by a.created_at desc
$$;

create or replace function public.acknowledge_alert(
    p_alert_id bigint,
    p_staff_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.alerts
    set status = 'acknowledged',
        assigned_to = p_staff_id,
        acknowledged_at = coalesce(acknowledged_at, now())
    where id = p_alert_id;
end;
$$;

create or replace function public.close_alert(
    p_alert_id bigint,
    p_notes text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.alerts
    set status = 'closed',
        closed_at = now(),
        close_notes = p_notes
    where id = p_alert_id;
end;
$$;

create or replace function public.create_handoff_request(
    p_facility_id uuid,
    p_resident_id uuid,
    p_notes text default null
)
returns table (
    id bigint,
    request_token text
)
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.handoff_requests (facility_id, resident_id, notes)
    values (p_facility_id, p_resident_id, p_notes)
    returning handoff_requests.id, handoff_requests.request_token
    into id, request_token;

    return next;
end;
$$;

create or replace function public.resolve_handoff_request(p_alert_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.handoff_requests
    set resolved_at = now(),
        resolved_by = auth.uid()
    where request_token = p_alert_id
       or id::text = p_alert_id;
end;
$$;

create or replace function public.get_pending_handoffs(p_facility_id uuid)
returns table (
    id integer,
    "facilityId" text,
    "residentId" text,
    "createdAt" text,
    notes text
)
language sql
security definer
set search_path = public
as $$
    select
        hr.id::integer,
        hr.facility_id::text as "facilityId",
        hr.resident_id::text as "residentId",
        to_char(hr.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') as "createdAt",
        hr.notes
    from public.handoff_requests hr
    where hr.facility_id = p_facility_id
      and hr.resolved_at is null
    order by hr.created_at desc
$$;

create or replace function public.get_residents_for_facility(p_facility_id uuid)
returns table (
    id uuid,
    facility_id uuid,
    name text,
    risk_level text,
    date_of_birth text
)
language sql
security definer
set search_path = public
as $$
    select
        r.id,
        r.facility_id,
        r.name,
        r.risk_level,
        case
            when r.date_of_birth is null then null
            else to_char(r.date_of_birth, 'YYYY-MM-DD') || 'T00:00:00Z'
        end as date_of_birth
    from public.residents r
    where r.facility_id = p_facility_id
    order by r.name
$$;

create or replace function public.get_fall_summary_for_resident(
    p_resident_id uuid,
    p_days integer default 7
)
returns integer
language sql
security definer
set search_path = public
as $$
    select count(*)::integer
    from public.alerts a
    where a.resident_id = p_resident_id
      and a.type = 'fall'
      and a.created_at >= now() - make_interval(days => greatest(coalesce(p_days, 7), 1))
$$;

create or replace function public.get_resident_timeline(
    p_resident_id uuid,
    p_limit integer default 50
)
returns table (
    kind text,
    ts text,
    summary text
)
language sql
security definer
set search_path = public
as $$
    with timeline as (
        select
            a.created_at as event_time,
            a.type as kind,
            initcap(a.type) || ' alert (' || a.status || ')' as summary
        from public.alerts a
        where a.resident_id = p_resident_id
        union all
        select
            v.observed_at as event_time,
            'vital' as kind,
            initcap(replace(v.metric, '_', ' ')) || ': ' || trim(to_char(v.value, 'FM999999990.00')) as summary
        from public.vital_events v
        where v.resident_id = p_resident_id
    )
    select
        timeline.kind,
        to_char(timeline.event_time at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') as ts,
        timeline.summary
    from timeline
    order by timeline.event_time desc
    limit greatest(coalesce(p_limit, 50), 1)
$$;

create or replace function public.record_vital_event(
    p_facility_id uuid,
    p_resident_id uuid,
    p_metric text,
    p_value double precision,
    p_timestamp timestamptz
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.vital_events (facility_id, resident_id, metric, value, observed_at, recorded_by)
    values (p_facility_id, p_resident_id, p_metric, p_value, coalesce(p_timestamp, now()), auth.uid());
end;
$$;

create or replace function public.get_facility_stats(p_facility_id uuid)
returns table (
    falls_last_7d integer,
    open_alerts integer,
    avg_acknowledge_minutes integer
)
language sql
security definer
set search_path = public
as $$
    select
        count(*) filter (
            where a.type = 'fall'
              and a.created_at >= now() - interval '7 days'
        )::integer as falls_last_7d,
        count(*) filter (where a.status <> 'closed')::integer as open_alerts,
        coalesce(
            avg(
                case
                    when a.acknowledged_at is not null then extract(epoch from (a.acknowledged_at - a.created_at)) / 60.0
                end
            )::integer,
            0
        ) as avg_acknowledge_minutes
    from public.alerts a
    where a.facility_id = p_facility_id
$$;

grant usage on schema public to anon, authenticated;

grant execute on function public.get_staff_info(uuid) to authenticated;

grant execute on function public.create_fall_alert(uuid, uuid, integer) to anon, authenticated;
grant execute on function public.create_sos_alert(uuid, uuid) to anon, authenticated;
grant execute on function public.get_open_alerts_for_facility(uuid) to anon, authenticated;
grant execute on function public.acknowledge_alert(bigint, uuid) to anon, authenticated;
grant execute on function public.close_alert(bigint, text) to anon, authenticated;

grant execute on function public.create_handoff_request(uuid, uuid, text) to anon, authenticated;
grant execute on function public.resolve_handoff_request(text) to anon, authenticated;
grant execute on function public.get_pending_handoffs(uuid) to anon, authenticated;

grant execute on function public.get_residents_for_facility(uuid) to anon, authenticated;
grant execute on function public.get_fall_summary_for_resident(uuid, integer) to anon, authenticated;
grant execute on function public.get_resident_timeline(uuid, integer) to anon, authenticated;
grant execute on function public.record_vital_event(uuid, uuid, text, double precision, timestamptz) to anon, authenticated;
grant execute on function public.get_facility_stats(uuid) to anon, authenticated;
